// scripts/write-env.mjs
// Writes src/environments/environment.ts from environment variables (CI)
// or from a local .env file (your machine). The file is gitignored.
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';

function readDotEnv(path = '.env') {
  if (!existsSync(path)) return {};
  const entries = readFileSync(path, 'utf8')
    .split(/\r?\n/)
    .map((line) => line.trim())
    .filter((line) => line && !line.startsWith('#') && line.includes('='))
    .map((line) => {
      const i = line.indexOf('=');
      const key = line.slice(0, i).trim();
      const value = line.slice(i + 1).trim().replace(/^["']|["']$/g, '');
      return [key, value];
    });
  return Object.fromEntries(entries);
}

const fileEnv = readDotEnv();
const get = (key) => process.env[key] || fileEnv[key] || '';

const config = {
  appEnv: get('APP_ENV') || 'development',
  supabaseUrl: get('SUPABASE_URL'),
  supabasePublishableKey: get('SUPABASE_PUBLISHABLE_KEY'),
};

const missing = Object.entries(config)
  .filter(([, value]) => !value)
  .map(([key]) => key);
if (missing.length) {
  console.error(`write-env: missing ${missing.join(', ')} (set them in .env or as CI variables)`);
  process.exit(1);
}

if (!/^https:\/\/[a-z0-9-]+\.supabase\.co$/.test(config.supabaseUrl)) {
  console.warn(`write-env: SUPABASE_URL looks unusual: ${config.supabaseUrl}`);
}

mkdirSync('src/environments', { recursive: true });
writeFileSync(
  'src/environments/environment.ts',
  `// Generated by scripts/write-env.mjs. Do not edit or commit.\n` +
    `export const environment = ${JSON.stringify(config, null, 2)} as const;\n`,
);
console.log(`write-env: wrote environment.ts for ${config.appEnv}`);